export enum USER_ROLE {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
  FREELANCER = "FREELANCER",
}

export enum LOGIN_METHOD {
  PHONE = "PHONE",
  EMAIL = "EMAIL",
}
export enum SIGN_UP_STEP {
  FORM = "FORM",
  OTP = "OTP",
  DONE = "DONE",
}

export enum EXPERIENCE_LEVEL {
  LESS_THAN_ONE_YEAR,
  ONE_TO_THREE_YEARS,
  THREE_TO_FIVE_YEARS,
  FIVE_TO_TEN_YEARS,
  MORE_THAN_TEN_YEARS,
}
